export const ticker: Record<string, { company: string; country: string }> = {
  AAPL: { company: '애플', country: '' },
  MSFT: { company: '마이크로소프트', country: '' },
  NVDA: { company: '엔비디아', country: '' },
  AMZN: { company: '아마존', country: '' },
  GOOG: { company: '알파벳 A', country: '' },
  GOOGL: { company: '알파벳 C', country: '' },
  META: { company: '메타', country: '' },
  TSLA: { company: '테슬라', country: '' },
  AVGO: { company: '브로드컴', country: '' },
  TSM: { company: 'TSMC', country: 'TW' },
  'BRK-A': { company: '버크셔 해서웨이 A', country: '' },
  'BRK-B': { company: '버크셔 해서웨이 B', country: '' },
  WMT: { company: '월마트', country: '' },
  LLY: { company: '일라이 릴리', country: '' },
  JPM: { company: 'JP모건 체이스', country: '' },
  V: { company: '비자', country: '' },
  MA: { company: '마스터카드', country: '' },
  UNH: { company: '유나이티드헬스 그룹', country: '' },
  XOM: { company: '엑손 모빌', country: '' },
  ORCL: { company: '오라클', country: '' },
  COST: { company: '코스트코', country: '' },
  NFLX: { company: '넷플릭스', country: '' },
  HD: { company: '홈디포', country: '' },
  PG: { company: '프록터 앤드 갬블', country: '' },
  JNJ: { company: '존슨앤드존슨', country: '' },
  BAC: { company: '뱅크 오브 아메리카', country: '' },
  ABBV: { company: '애브비', country: '' },
  CRM: { company: '세일즈포스', country: '' },
  SAP: { company: 'SAP', country: 'DE' },
  ASML: { company: 'ASML 홀딩', country: 'NL' },
  NVO: { company: '노보 노디스크', country: 'DK' },
  TMUS: { company: 'T-모바일', country: '' },
  CVX: { company: '셰브론', country: '' },
  KO: { company: '코카콜라', country: '' },
  WFC: { company: '웰스파고', country: '' },
  TM: { company: '토요타 모터', country: 'JP' },
  CSCO: { company: '시스코 시스템즈', country: '' },
  ACN: { company: '액센츄어', country: 'IE' },
  IBM: { company: 'IBM', country: '' },
  BABA: { company: '알리바바', country: 'CN' },
  PLTR: { company: '팔란티어 테크놀로지스', country: '' },
  ABT: { company: '애보트 래버러토리스', country: '' },
  MRK: { company: '머크앤코', country: '' },
  AXP: { company: '아메리칸 익스프레스', country: '' },
  MS: { company: '모건 스탠리', country: '' },
  TMO: { company: '써모 피셔 사이언티픽', country: '' },
  AZN: { company: '아스트라제네카', country: 'GB' },
  GE: { company: 'GE 에어로스페이스', country: '' },
  NVS: { company: '노바티스', country: 'CH' },
  LIN: { company: '린데', country: 'GB' },
  BX: { company: '블랙스톤', country: '' },
  NOW: { company: '서비스나우', country: '' },
  ISRG: { company: '인튜이티브 서지컬', country: '' },
  MCD: { company: '맥도날드', country: '' },
  PM: { company: '필립 모리스 인터내셔널', country: '' },
  SHEL: { company: '쉘', country: 'GB' },
  GS: { company: '골드만삭스', country: '' },
  DIS: { company: '월트 디즈니', country: '' },
  PEP: { company: '펩시코', country: '' },
  QCOM: { company: '퀄컴', country: '' },
  ADBE: { company: '어도비', country: '' },
  HSBC: { company: 'HSBC', country: 'GB' },
  ARM: { company: 'Arm 홀딩스', country: 'GB' },
  AMD: { company: 'AMD', country: '' },
  T: { company: 'AT&T', country: '' },
  CAT: { company: '캐터필러', country: '' },
  RTX: { company: 'RTX', country: '' },
  VZ: { company: '버라이즌 커뮤니케이션스', country: '' },
  RY: { company: '로열 뱅크 오브 캐나다', country: 'CA' },
  TXN: { company: '텍사스 인스트루먼트', country: '' },
  AMGN: { company: '암젠', country: '' },
  INTU: { company: '인튜이트', country: '' },
  SPGI: { company: 'S&P 글로벌', country: '' },
  SHOP: { company: '쇼피파이', country: 'CA' },
  BLK: { company: '블랙록', country: '' },
  HDB: { company: 'HDFC 뱅크', country: 'IN' },
  BKNG: { company: '부킹 홀딩스', country: '' },
  BSX: { company: '보스턴 사이언티픽', country: '' },
  DHR: { company: '다나허', country: '' },
  PDD: { company: 'PDD 홀딩스', country: 'CN' },
  SYK: { company: '스트라이커', country: '' },
  SCHW: { company: '찰스 슈왑', country: '' },
  PFE: { company: '화이자', country: '' },
  C: { company: '씨티그룹', country: '' },
  UNP: { company: '유니온 퍼시픽', country: '' },
  AMAT: { company: '어플라이드 머티어리얼즈', country: '' },
  MUFG: { company: '미쓰비시 UFJ 파이낸셜', country: 'JP' },
  LOW: { company: '로우스 컴퍼니', country: '' },
  PGR: { company: '프로그레시브', country: '' },
  ANET: { company: '아리스타 네트웍스', country: '' },
  HON: { company: '허니웰 인터내셔널', country: '' },
  UL: { company: '유니레버', country: 'GB' },
  NEE: { company: '넥스트에라 에너지', country: '' },
  TJX: { company: 'TJX 컴퍼니스', country: '' },
  TTE: { company: '토탈에너지스', country: 'FR' },
  KKR: { company: 'KKR & Co', country: '' },
  BA: { company: '보잉', country: '' },
  SONY: { company: '소니 그룹', country: 'JP' },
  UBER: { company: '우버 테크놀로지스', country: '' },
  SNY: { company: '사노피', country: 'FR' },
  FI: { company: '파이서브', country: '' },
  COP: { company: '코노코필립스', country: '' },
  CMCSA: { company: '컴캐스트', country: '' },
  SBUX: { company: '스타벅스', country: '' },
  DE: { company: '디어 앤 코', country: '' },
  BHP: { company: 'BHP 그룹', country: 'AU' },
  VRTX: { company: '버텍스 파마슈티컬', country: '' },
  ADP: { company: '오토매틱 데이터 프로세싱', country: '' },
  ETN: { company: '이튼', country: 'IE' },
  GILD: { company: '길리어드 사이언스', country: '' },
  APP: { company: '앱플로빈', country: '' },
  SPOT: { company: '스포티파이', country: 'LU' },
  PANW: { company: '팰로 앨토 네트웍스', country: '' },
  BMY: { company: '브리스톨 마이어스 스퀴브', country: '' },
  MDT: { company: '메드트로닉', country: 'IE' },
  PLD: { company: '프로로지스', country: '' },
  MMC: { company: '마쉬 앤 맥레넌 컴퍼니', country: '' },
  NKE: { company: '나이키', country: '' },
  CB: { company: '처브', country: 'CH' },
  LMT: { company: '록히드 마틴', country: '' },
  LRCX: { company: '램 리서치', country: '' },
  MU: { company: '마이크론 테크놀로지', country: '' },
  ADI: { company: '아날로그 디바이스', country: '' },
  UBS: { company: 'UBS 그룹', country: 'CH' },
  IBN: { company: 'ICICI 뱅크', country: 'IN' },
  CRWD: { company: '크라우드스트라이크 홀딩스', country: '' },
  GEV: { company: 'GE 버노바', country: '' },
  KLAC: { company: 'KLA', country: '' },
  MRVL: { company: '마벨 테크놀로지', country: '' },
  TD: { company: '토론토 도미니언 뱅크', country: 'CA' },
  MELI: { company: '메르카도리브레', country: '' },
  IBKR: { company: '인터랙티브 브로커스 그룹', country: '' },
  CEG: { company: '콘스텔레이션 에너지', country: '' },
  SMFG: { company: '스미토모 미쓰이 파이낸셜 그룹', country: 'JP' },
  ENB: { company: '엔브리지', country: 'CA' },
  UPS: { company: '유나이티드 파셀 서비스', country: '' },
  RELX: { company: 'RELX', country: 'GB' },
  APO: { company: '아폴로 글로벌 매니지먼트', country: '' },
  ELV: { company: '엘레반스 헬스', country: '' },
  INFY: { company: '인포시스', country: 'IN' },
  ICE: { company: '인터컨티넨탈 익스체인지', country: '' },
  SO: { company: '서던', country: '' },
  SHW: { company: '셔윈 윌리암스', country: '' },
  BTI: { company: '브리티쉬 아메리칸 토바코', country: 'GB' },
  EQIX: { company: '에퀴닉스', country: '' },
  WM: { company: '웨이스트 매니지먼트', country: '' },
  BN: { company: '브룩필드', country: 'CA' },
  MCO: { company: '무디스', country: '' },
  MO: { company: '알트리아 그룹', country: '' },
  PH: { company: '파카 하니핀', country: '' },
  WELL: { company: '웰타워', country: '' },
  DUK: { company: '듀크 에너지', country: '' },
  AMT: { company: '아메리칸 타워', country: '' },
  CME: { company: 'CME 그룹', country: '' },
  BUD: { company: '앤하이저부시 인베브', country: 'BE' },
  HCA: { company: 'HCA 헬스케어', country: '' },
  INTC: { company: '인텔', country: '' },
  MSTR: { company: '스트래티지', country: '' },
  TEAM: { company: '아틀라시안', country: '' },
  APH: { company: '암페놀', country: '' },
  SAN: { company: '방코 산탄데르', country: 'ES' },
  RACE: { company: '페라리', country: 'IT' },
  CDNS: { company: '케이던스 디자인 시스템즈', country: '' },
  BP: { company: 'BP', country: 'GB' },
  AON: { company: '에이온', country: 'IE' },
  MMM: { company: '3M', country: '' },
  ABNB: { company: '에어비앤비', country: '' },
  SNPS: { company: '시놉시스', country: '' },
  CI: { company: '시그나 그룹', country: '' },
  DASH: { company: '도어대시', country: '' },
  CTAS: { company: '신타스', country: '' },
  MAR: { company: '메리어트 인터내셔널', country: '' },
  FTNT: { company: '포티넷', country: '' },
  TT: { company: '트레인 테크놀로지', country: 'IE' },
  MSI: { company: '모토로라 솔루션스', country: '' },
  ZTS: { company: '조에티스', country: '' },
  AJG: { company: '아서 J 갤러거 앤 코', country: '' },
  PNC: { company: 'PNC 파이낸셜 서비스 그룹', country: '' },
  REGN: { company: '리제네론 파마슈티컬스', country: '' },
  CMG: { company: '치폴레 멕시칸 그릴', country: '' },
  PYPL: { company: '페이팔 홀딩스', country: '' },
  ORLY: { company: '오릴리 오토모티브', country: '' },
  COF: { company: '캐피털 원 파이낸셜', country: '' },
  MCK: { company: '매케슨', country: '' },
  GSK: { company: 'GSK', country: 'GB' },
  RIO: { company: '리오 틴토', country: 'GB' },
  MDLZ: { company: '몬덜리즈 인터내셔널', country: '' },
  TRI: { company: '톰슨 로이터', country: 'CA' },
  ITW: { company: '일리노이 툴 웍스', country: '' },
  APD: { company: '에어 프로덕츠 앤 케미컬스', country: '' },
  USB: { company: 'US 뱅코프', country: '' },
  SCCO: { company: '서던 코퍼', country: '' },
  WDAY: { company: '워크데이', country: '' },
  DELL: { company: '델 테크놀로지스', country: '' },
  CP: { company: '캐나디안 퍼시픽 레일웨이', country: 'CA' },
  TDG: { company: '트랜스다임 그룹', country: '' },
  BMO: { company: '뱅크 오브 몬트리올', country: 'CA' },
  EOG: { company: 'EOG 리소시스', country: '' },
  RCL: { company: '로얄 캐리비안 크루즈', country: '' },
  EPD: { company: '엔터프라이즈 프로덕츠 파트너스', country: '' },
  ET: { company: '에너지 트랜스퍼', country: '' },
  GD: { company: '제너럴 다이내믹스', country: '' },
  BDX: { company: '벡톤 디킨슨', country: '' },
  EMR: { company: '에머슨 일렉트릭', country: '' },
  CL: { company: '콜게이트-팜올리브', country: '' },
  ECL: { company: '이콜랩', country: '' },
  CVS: { company: 'CVS 헬스', country: '' },
  MFG: { company: '미즈호 파이낸셜 그룹', country: 'JP' },
  WMB: { company: '윌리엄스 컴퍼니즈', country: '' },
  RSG: { company: '리퍼블릭 서비스', country: '' },
  COIN: { company: '코인베이스 글로벌', country: '' },
  CRH: { company: 'CRH', country: '' },
  NOC: { company: '노스롭 그루먼', country: '' },
  SPG: { company: '사이먼 프로퍼티 그룹', country: '' },
  ADSK: { company: '오토데스크', country: '' },
  BBVA: { company: '방코 빌바오 비스카야 아르헨타리아', country: 'ES' },
  CNQ: { company: '캐나디안 내추럴 리소시스', country: 'CA' },
  CNI: { company: '캐나디안 내셔널 레일웨이', country: 'CA' },
  SE: { company: '씨', country: 'SG' },
  NU: { company: '누 홀딩스', country: 'KY' },
  EQNR: { company: '에퀴노르', country: 'NO' },
  CSX: { company: 'CSX', country: '' },
  TFC: { company: '트루이스트 파이낸셜', country: '' },
  NTES: { company: '넷이즈', country: 'CN' },
  HLT: { company: '힐튼 월드와이드 홀딩스', country: '' },
  SNOW: { company: '스노우플레이크', country: '' },
  ROP: { company: '로퍼 테크놀로지스', country: '' },
  BNS: { company: '뱅크 오브 노바 스코샤', country: 'CA' },
  TGT: { company: '타겟', country: '' },
  DEO: { company: '디아지오', country: 'GB' },
  BK: { company: '뱅크 오브 뉴욕 멜론', country: '' },
  KMI: { company: '킨더 모건', country: '' },
  NGG: { company: '내셔널 그리드', country: 'GB' },
  OKE: { company: '원오크', country: '' },
  FDX: { company: '페덱스', country: '' },
  AFL: { company: '애플랙', country: '' },
  ARES: { company: '아레스 매니지먼트', country: '' },
  MET: { company: '메트라이프', country: '' },
  VST: { company: '비스트라 에너지', country: '' },
  AZO: { company: '오토존', country: '' },
  CARR: { company: '캐리어 글로벌', country: '' },
  CM: { company: '캐나디안 임페리얼 뱅크 오브 커머스', country: 'CA' },
  SLB: { company: '슐럼버거', country: '' },
  NSC: { company: '노퍽 서던', country: '' },
  JCI: { company: '존슨 콘트롤즈 인터내셔널', country: 'IE' },
  CPRT: { company: '코파트', country: '' },
  TTD: { company: '트레이드 데스크', country: '' },
  PCAR: { company: '파카', country: '' },
  TRV: { company: '트래블러스 컴퍼니스', country: '' },
  DLR: { company: '디지털 리얼티 트러스트', country: '' },
  JD: { company: '징동닷컴', country: 'CN' },
  MPLX: { company: 'MPLX', country: '' },
  CHTR: { company: '차터 커뮤니케이션즈', country: '' },
  PAYX: { company: '페이첵스', country: '' },
  NXPI: { company: 'NXP 세미컨덕터스', country: 'NL' },
  BCS: { company: '바클리즈', country: 'GB' },
  XYZ: { company: '블록', country: '' },
  CVNA: { company: '카바나', country: '' },
  AEP: { company: '아메리칸 일렉트릭 파워 컴퍼니', country: '' },
  PSA: { company: '퍼블릭 스토리지', country: '' },
  FCX: { company: '프리포트 맥모란', country: '' },
  LULU: { company: '룰루레몬 애슬레티카', country: 'CA' },
  MFC: { company: '매뉴라이프 파이낸셜', country: 'CA' },
  AMP: { company: '아메리프라이즈 파이낸셜', country: '' },
  SRE: { company: '셈프라', country: '' },
  HWM: { company: '하우멧 에어로스페이스', country: '' },
  AXON: { company: '액손 엔터프라이즈', country: '' },
  PBR: { company: '페트로브라스', country: 'BR' },
  LNG: { company: '셰니어 에너지', country: '' },
  NEM: { company: '뉴몬트', country: '' },
  ALL: { company: '올스테이트', country: '' },
  PSX: { company: '필립스 66', country: '' },
  GWW: { company: 'W W 그레인저', country: '' },
  CMI: { company: '커민스', country: '' },
  DFS: { company: '디스커버 파이낸셜 서비스', country: '' },
  MPC: { company: '마라톤 페트롤리움', country: '' },
  ING: { company: 'ING 그룹', country: 'NL' },
  RBLX: { company: '로블록스', country: '' },
  NET: { company: '클라우드플레어', country: '' },
  AEM: { company: '애그니코 이글 마인스', country: 'CA' },
  DDOG: { company: '데이터독', country: '' },
  COR: { company: '센코라', country: '' },
  TRP: { company: 'TC 에너지', country: 'CA' },
  WCN: { company: '웨이스트 커넥션스', country: 'CA' },
  ROST: { company: '로스 스토어스', country: '' },
  SU: { company: '선코어 에너지', country: 'CA' },
  BKR: { company: '베이커 휴즈', country: '' },
  URI: { company: '유나이티드 렌탈스', country: '' },
  FANG: { company: '다이아몬드백 에너지', country: '' },
  HOOD: { company: '로빈후드', country: '' },
  O: { company: '리얼티 인컴', country: '' },
  NDAQ: { company: '나스닥', country: '' },
  VG: { company: '벤처 글로벌', country: '' },
  GM: { company: '제너럴 모터스', country: '' },
  KR: { company: '크로거', country: '' },
  FLUT: { company: '플러터 엔터테인먼트', country: 'GB' },
  LYG: { company: '로이즈 뱅킹 그룹', country: 'GB' },
  ALC: { company: '알콘', country: 'CH' },
  AIG: { company: '아메리칸 인터내셔널 그룹', country: '' },
  GLW: { company: '코닝', country: '' },
  MSCI: { company: 'MSCI', country: '' },
  D: { company: '도미니언 에너지', country: '' },
  E: { company: '에니 SpA', country: 'IT' },
  FICO: { company: '페어 아이작', country: '' },
  CBRE: { company: 'CBRE 그룹', country: '' },
  MNST: { company: '몬스터 베버리지', country: '' },
  HMC: { company: '혼다 모터스', country: 'JP' },
  VRT: { company: '버티브 홀딩스', country: '' },
  TRGP: { company: '타르가 리소시스', country: '' },
  DAL: { company: '델타 항공', country: '' },
  NWG: { company: '냇웨스트 그룹', country: 'GB' },
  VLO: { company: '발레로 에너지', country: '' },
  OXY: { company: '옥시덴탈 페트롤리움', country: '' },
  TCOM: { company: '트립닷컴 그룹', country: 'CN' },
  FIS: { company: '피델리티 내셔널 인포메이션 서비스', country: '' },
  PWR: { company: '콴타 서비스', country: '' },
  HES: { company: '헤스', country: '' },
  CTVA: { company: '코르테바', country: '' },
  DHI: { company: 'D.R. 호튼', country: '' },
  TEL: { company: 'TE 커넥티비티', country: 'IE' },
  HLN: { company: '헤일리온', country: 'GB' },
  AMX: { company: '아메리카 모빌 L', country: 'MX' },
  CPNG: { company: '쿠팡', country: '' },
  KMB: { company: '킴벌리클라크', country: '' },
  EW: { company: '에드워즈 라이프사이언시스', country: '' },
  TAK: { company: '다케다 파마슈티컬', country: 'JP' },
  KDP: { company: '큐리그 닥터페퍼', country: '' },
  A: { company: '애질런트 테크놀로지스', country: '' },
  FAST: { company: '패스널', country: '' },
  GRMN: { company: '가민', country: 'CH' },
  PEG: { company: '퍼블릭 서비스 엔터프라이즈 그룹', country: '' },
  IT: { company: '가트너', country: '' },
  AME: { company: '아메텍', country: '' },
  CTSH: { company: '코그니전트 테크놀로지 솔루션즈', country: '' },
  ODFL: { company: '올드 도미니언 프레이트 라인', country: '' },
  EXC: { company: '엑셀론', country: '' },
  VRSK: { company: '베리스크 애널리틱스', country: '' },
  ARGX: { company: '아르젠엑스', country: 'NL' },
  PRU: { company: '푸르덴셜 파이낸셜', country: '' },
  HUBS: { company: '허브스팟', country: '' },
  VALE: { company: '발리', country: 'BR' },
  GEHC: { company: 'GE 헬스케어', country: '' },
  F: { company: '포드 모터', country: '' },
  KVUE: { company: '켄뷰', country: '' },
  LHX: { company: 'L3해리스 테크놀로지스', country: '' },
  CCI: { company: '크라운 캐슬', country: '' },
  XEL: { company: '엑셀 에너지', country: '' },
  VEEV: { company: '비바 시스템즈', country: '' },
  RDDT: { company: '레딧', country: '' },
  WIT: { company: '위프로', country: 'IN' },
  IDXX: { company: '아이덱스 래버러토리스', country: '' },
  OTIS: { company: '오티스 월드와이드', country: '' },
  IQV: { company: '아이큐비아 홀딩스', country: '' },
  STLA: { company: '스텔란티스', country: 'NL' },
  OWL: { company: '블루 아울 캐피탈', country: '' },
  IR: { company: '잉가솔랜드', country: '' },
  DKNG: { company: '드래프트킹스', country: '' },
  YUM: { company: '염 브랜즈', country: '' },
  FERG: { company: '퍼거슨 엔터프라이즈', country: '' },
  CCEP: { company: '코카콜라 유로퍼시픽 파트너스', country: 'GB' },
  VMC: { company: '벌칸 머티리얼스', country: '' },
  DB: { company: '도이체 방크', country: 'DE' },
  ALNY: { company: '앨나일람 파마슈티컬스', country: '' },
  RMD: { company: '레즈메드', country: '' },
  WAB: { company: '웨스팅하우스 에어 브레이크 테크놀로지', country: '' },
  UAL: { company: '유나이티드 항공', country: '' },
  ETR: { company: '엔터지', country: '' },
  CCL: { company: '카니발', country: '' },
  ACGL: { company: '아치 캐피탈 그룹', country: 'BM' },
  HUM: { company: '휴매나', country: '' },
  SYY: { company: '시스코', country: '' },
  IMO: { company: '임페리얼 오일', country: 'CA' },
  DXCM: { company: '덱스콤', country: '' },
  KHC: { company: '크래프트 하인즈', country: '' },
  PCG: { company: 'PG&E', country: '' },
  LYV: { company: '라이브 네이션 엔터테인먼트', country: '' },
  EA: { company: '일렉트로닉 아츠', country: '' },
  EXR: { company: '엑스트라 스페이스 스토리지', country: '' },
  RJF: { company: '레이먼드 제임스 파이낸셜', country: '' },
  LEN: { company: '레나', country: '' },
  'PBR-A': { company: '페트로브라스 우선주', country: 'BR' },
  EFX: { company: '에퀴팩스', country: '' },
  SLF: { company: '선 라이프 파이낸셜', country: 'CA' },
  ED: { company: '콘솔리데이티드 에디슨', country: '' },
  MLM: { company: '마틴 마리에타 머티리얼스', country: '' },
  MTB: { company: 'M&T 뱅크', country: '' },
  HIG: { company: '하트포드 파이낸셜 서비스 그룹', country: '' },
  GIS: { company: '제너럴 밀스', country: '' },
  TTWO: { company: '테이크투 인터랙티브 소프트웨어', country: '' },
  WTW: { company: '윌리스 타워스 왓슨', country: 'GB' },
  EBAY: { company: '이베이', country: '' },
  DD: { company: '듀폰', country: '' },
  WEC: { company: 'WEC 에너지 그룹', country: '' },
  TPL: { company: '텍사스 퍼시픽 랜드', country: '' },
  AVB: { company: '아발론베이 커뮤니티', country: '' },
  MPWR: { company: '모놀리틱 파워 시스템', country: '' },
  CSGP: { company: '코스타 그룹', country: '' },
  EQT: { company: 'EQT', country: '' },
  LVS: { company: '라스베가스 샌즈', country: '' },
  VICI: { company: 'VICI 프로퍼티', country: '' },
  XYL: { company: '자일럼', country: '' },
  ZS: { company: '지스케일러', country: '' },
  NUE: { company: '뉴코', country: '' },
  CQP: { company: '셰니에르 에너지 파트너스', country: '' },
  STZ: { company: '컨스텔레이션 브랜드', country: '' },
  CAH: { company: '카디널 헬스', country: '' },
  KEYS: { company: '키사이트 테크놀로지스', country: '' },
  CNC: { company: '센틴', country: '' },
  ROK: { company: '로크웰 오토메이션', country: '' },
  HPQ: { company: 'HP', country: '' },
  BRO: { company: '브라운 앤 브라운', country: '' },
  IRM: { company: '아이언 마운틴', country: '' },
  ANSS: { company: '앤시스', country: '' },
  FER: { company: '페로비알', country: 'NL' },
  IOT: { company: '삼사라', country: '' },
  FCNCA: { company: '퍼스트 시티즌스 뱅크셰어스', country: '' },
  GOLD: { company: '배릭 골드', country: 'CA' },
  WPM: { company: '휘턴 프레셔스 메탈스', country: 'CA' },
  CHT: { company: '중화 텔레콤', country: 'TW' },
  WDS: { company: '우드사이드 에너지 그룹', country: 'AU' },
  TW: { company: '트레이드웹 마켓', country: '' },
  HSY: { company: '허쉬', country: '' },
  FITB: { company: '피프스 서드 뱅코프', country: '' },
  GDDY: { company: '고대디', country: '' },
  BNTX: { company: '바이오엔텍', country: 'DE' },
  'HEI-A': { company: '헤이코 A', country: '' },
  HEI: { company: '헤이코', country: '' },
  ABEV: { company: '암베브', country: 'BR' },
  MTD: { company: '메틀러 톨레도 인터내셔널', country: '' },
  ITUB: { company: '이타우 우니방코 홀딩스', country: 'BR' },
  MCHP: { company: '마이크로칩 테크놀로지', country: '' },
  STT: { company: '스테이트 스트리트', country: '' },
  TSCO: { company: '트랙터 서플라이', country: '' },
  GPN: { company: '글로벌 페이먼츠', country: '' },
  SW: { company: '스머핏 웨스트록', country: 'IE' },
  K: { company: '켈라노바', country: '' },
  EQR: { company: '에쿼티 레지덴셜', country: '' },
  HPE: { company: '휴렛 팩커드 엔터프라이즈', country: '' },
  BR: { company: '브로드리지 파이낸셜 솔루션즈', country: '' },
  DOV: { company: '도버', country: '' },
  FTV: { company: '포티브', country: '' },
  CVE: { company: '세노버스 에너지', country: 'CA' },
  TKO: { company: 'TKO 그룹 홀딩스', country: '' },
  CDW: { company: 'CDW', country: '' },
  LPLA: { company: 'LPL 파이낸셜 홀딩스', country: '' },
  FNV: { company: '프랑코 네바다', country: 'CA' },
  CPAY: { company: '코페이', country: '' },
  GIB: { company: 'CGI', country: 'CA' },
  DOW: { company: '다우', country: '' },
  SYF: { company: '싱크로니 파이낸셜', country: '' },
  TYL: { company: '타일러 테크놀로지스', country: '' },
  ZM: { company: '줌 커뮤니케이션', country: '' },
  CHD: { company: '처치 앤 드와이트', country: '' },
  VTR: { company: '벤타스', country: '' },
  DECK: { company: '데커스 아웃도어', country: '' },
  PPG: { company: 'PPG 인더스트리스', country: '' },
  NOK: { company: '노키아', country: 'FI' },
  AEE: { company: '애머런', country: '' },
  WSM: { company: '윌리엄스 소노마', country: '' },
  UI: { company: '유비퀴티', country: '' },
  PHG: { company: '필립스', country: 'NL' },
  RYAAY: { company: '라이언에어 홀딩스', country: 'IE' },
  NTR: { company: '뉴트리엔', country: 'CA' },
  DTE: { company: 'DTE 에너지', country: '' },
  RKT: { company: '로켓 컴퍼니스', country: '' },
  NTAP: { company: '넷앱', country: '' },
  PPL: { company: 'PPL', country: '' },
  LYB: { company: '라이온델바젤 인더스트리스', country: 'GB' },
  WBD: { company: '워너 브로스 디스커버리', country: '' },
  BIDU: { company: '바이두', country: 'CN' },
  TROW: { company: '티 로웨 프라이스 그룹', country: '' },
  WAT: { company: '워터스', country: '' },
  HBAN: { company: '헌팅턴 뱅크셰어스', country: '' },
  EXE: { company: '익스팬드 에너지', country: '' },
  WST: { company: '웨스트 파마슈티컬 서비시즈', country: '' },
  BAM: { company: '브룩필드 애셋 매니지먼트', country: 'CA' },
  FOX: { company: '폭스 B', country: '' },
  FOXA: { company: '폭스 A', country: '' },
  AWK: { company: '아메리칸 워터 웍스', country: '' },
  ROL: { company: '롤린스', country: '' },
  TDY: { company: '텔레다인 테크놀로지스', country: '' },
  MKL: { company: '마켈 그룹', country: '' },
  NVR: { company: 'NVR', country: '' },
  CHKP: { company: '체크 포인트 소프트웨어 테크놀로지스', country: 'IL' },
  VLTO: { company: '베랄토', country: '' },
  EL: { company: '에스티 로더', country: '' },
  FWONK: { company: '리버티 미디어 포뮬러 원 C', country: '' },
  DRI: { company: '다든 레스토랑', country: '' },
  TOST: { company: '토스트', country: '' },
  NTRA: { company: '나테라', country: '' },
  ERIC: { company: '에릭슨 B', country: 'SE' },
  TPG: { company: 'TPG', country: '' },
  WRB: { company: 'W.R. 버클리', country: '' },
  IX: { company: '오릭스', country: 'JP' },
  FE: { company: '퍼스트에너지', country: '' },
  HAL: { company: '할리버튼', country: '' },
  TEF: { company: '텔레포니카', country: 'ES' },
  ATO: { company: '애트모스 에너지', country: '' },
  PTC: { company: 'PTC', country: '' },
  PHM: { company: '풀티 그룹', country: '' },
  PSTG: { company: '퓨어 스토리지', country: '' },
  BCE: { company: 'BCE', country: 'CA' },
  KB: { company: 'KB 파이낸셜 그룹', country: 'KR' },
  TWLO: { company: '트윌리오', country: '' },
  GFS: { company: '글로벌파운드리스', country: '' },
  WDC: { company: '웨스턴 디지털', country: '' },
  PINS: { company: '핀터레스트', country: '' },
  VIK: { company: '바이킹 홀딩스', country: 'BM' },
  NTRS: { company: '노던 트러스트', country: '' },
  DVN: { company: '데번 에너지', country: '' },
  ONC: { company: '베이진', country: 'KY' },
  ADM: { company: '아처 대니얼스 미들랜드', country: '' },
  RF: { company: '리전스 파이낸셜', country: '' },
  WY: { company: '와이어하우저', country: '' },
  IFF: { company: '인터내셔널 플레이버스 & 프레그런스', country: '' },
  ON: { company: '온 세미콘덕터', country: '' },
  TU: { company: '텔러스', country: 'CA' },
  CCJ: { company: '카메코', country: 'CA' },
  ASX: { company: 'ASE 테크놀로지 홀딩', country: 'TW' },
  FWONA: { company: '리버티 미디어 포뮬러 원 A', country: '' },
  SBAC: { company: 'SBA 커뮤니케이션스', country: '' },
  CBOE: { company: 'Cboe 글로벌 마켓', country: '' },
  STE: { company: '스테리스', country: 'IE' },
  TS: { company: '테나리스', country: 'LU' },
  EXPE: { company: '익스피디아', country: '' },
  FTS: { company: '포르티스', country: 'CA' },
  PUK: { company: '푸르덴셜', country: 'GB' },
  ZBH: { company: '짐머 바이오멧 홀딩스', country: '' },
  TECK: { company: '텍 리소스', country: 'CA' },
  BIP: { company: '브룩필드 인프라스트럭처 파트너스', country: 'BM' },
  HUBB: { company: '허벨', country: '' },
  ES: { company: '에버소스 에너지', country: '' },
  CINF: { company: '신시내티 파이낸셜', country: '' },
  PBA: { company: '펨비나 파이프라인', country: 'CA' },
  VRSN: { company: '베리사인', country: '' },
  BIIB: { company: '바이오젠', country: '' },
  IHG: { company: '인터컨티넨탈 호텔스 그룹', country: 'GB' },
  EDR: { company: '엔데버 그룹 홀딩스', country: '' },
  CNP: { company: '센터포인트 에너지', country: '' },
  EME: { company: '엠코 그룹', country: '' },
  MDB: { company: '몽고DB', country: '' },
  CFG: { company: '시티즌스 파이낸셜 그룹', country: '' },
  VOD: { company: '보다폰 그룹', country: 'GB' },
  LH: { company: '랩코프 홀딩스', country: '' },
  LII: { company: '레녹스 인터내셔널', country: '' },
  NRG: { company: 'NRG 에너지', country: '' },
  CTRA: { company: '코테라 에너지', country: '' },
  NMR: { company: '노무라 홀딩스', country: 'JP' },
  MKC: { company: '맥코믹 앤 컴퍼니', country: '' },
  EIX: { company: '에디슨 인터내셔널', country: '' },
  QSR: { company: '레스토랑 브랜즈 인터내셔널', country: 'CA' },
  SSNC: { company: 'SS&C 테크놀로지스 홀딩스', country: '' },
  STX: { company: '씨게이트 테크놀로지 홀딩스', country: '' },
  CMS: { company: 'CMS 에너지', country: '' },
  ZBRA: { company: '지브라 테크놀로지스', country: '' },
  MT: { company: '아르셀로미탈', country: 'LU' },
  PODD: { company: '인슐릿', country: '' },
  TSN: { company: '타이슨 푸드', country: '' },
  Z: { company: '질로우 그룹 C', country: '' },
  ZG: { company: '질로우 그룹 A', country: '' },
  STM: { company: 'ST 마이크로일렉트로닉스', country: 'NL' },
  ILMN: { company: '일루미나', country: '' },
  KEY: { company: '키코프', country: '' },
  AFRM: { company: '어펌 홀딩스', country: '' },
  STLD: { company: '스틸 다이내믹스', country: '' },
  ESS: { company: '에섹스 프로퍼티 트러스트', country: '' },
  DOCU: { company: '도큐사인', country: '' },
  AER: { company: '에어캡 홀딩스', country: 'IE' },
  TEVA: { company: '테바 파마슈티컬 인더스트리스', country: 'IL' },
  DKS: { company: '딕스 스포팅 굿즈', country: '' },
  EC: { company: '에코페트롤', country: 'CO' },
  INVH: { company: '인비테이션 홈즈', country: '' },
  COO: { company: '쿠퍼 컴퍼니스', country: '' },
  NTNX: { company: '뉴타닉스', country: '' },
  BEKE: { company: 'KE 홀딩스', country: 'CN' },
  WSO: { company: '와츠코', country: '' },
  LI: { company: '리 오토', country: 'CN' },
  ULTA: { company: '울타 뷰티', country: '' },
  ERIE: { company: '이리 인뎀니티', country: '' },
  CRBG: { company: '코어브릿지 파이낸셜', country: '' },
  ONON: { company: '온 홀딩', country: 'CH' },
  PKG: { company: '패키징 코퍼레이션 오브 아메리카', country: '' },
  LDOS: { company: '레이도스 홀딩스', country: '' },
  MAA: { company: '미드아메리카 아파트 커뮤니티', country: '' },
  CG: { company: '칼라일 그룹', country: '' },
  TRU: { company: '트랜스유니온', country: '' },
  L: { company: '로우스', country: '' },
  CYBR: { company: '사이버아크 소프트웨어', country: 'IL' },
  IP: { company: '인터내셔널 페이퍼', country: '' },
  SNA: { company: '스냅-온', country: '' },
  BLDR: { company: '빌더스 퍼스트소스', country: '' },
  KSPI: { company: '카스피.kz', country: 'KZ' },
  RPRX: { company: '로열티 파마', country: '' },
  LUV: { company: '사우스웨스트 항공', country: '' },
  BBY: { company: '베스트 바이', country: '' },
  TRMB: { company: '트림블', country: '' },
  SMCI: { company: '슈퍼 마이크로 컴퓨터', country: '' },
  PFG: { company: '프린시펄 파이낸셜 그룹', country: '' },
  DGX: { company: '퀘스트 다이아그노스틱스', country: '' },
  TER: { company: '테라다인', country: '' },
  GWRE: { company: '가이드와이어 소프트웨어', country: '' },
  SYM: { company: '심보틱', country: '' },
  MOH: { company: '몰리나 헬스케어', country: '' },
  DT: { company: '다이나트레이스', country: '' },
  GRAB: { company: '그랩 홀딩스스', country: 'SG' },
  RYAN: { company: '라이언 스페셜티 홀딩스', country: '' },
  CLX: { company: '크로락스', country: '' },
  JBL: { company: '자빌', country: '' },
  GFL: { company: 'GFL 인바이런멘털', country: 'CA' },
  FDS: { company: '팩트셋 리서치 시스템즈', country: '' },
  SNAP: { company: '스냅', country: '' },
  NI: { company: '나이소스', country: '' },
  BSBR: { company: '방코 산탄데르 브라질', country: 'BR' },
  FFIV: { company: 'F5', country: '' },
  FMX: { company: '포멘토 에코노미코 멕시카노', country: 'MX' },
  SHG: { company: '신한 파이낸셜 그룹', country: 'KR' },
  AS: { company: '아머 스포츠', country: 'FI' },
  FSLR: { company: '퍼스트 솔라', country: '' },
  YUMC: { company: '염 차이나 홀딩스', country: 'CN' },
  DUOL: { company: '듀오링고', country: '' },
  NWS: { company: '뉴스 코퍼레이션 B', country: '' },
  NWSA: { company: '뉴스 코퍼레이션 A', country: '' },
  JBHT: { company: 'JB 헌트 트랜스포트 서비스', country: '' },
  TPR: { company: '태피스트리', country: '' },
  BURL: { company: '벌링턴 스토어스', country: '' },
  GEN: { company: '젠 디지털', country: '' },
  SFM: { company: '스프라우츠 파머스 마켓', country: '' },
  ALAB: { company: '아스테라 랩스', country: '' },
  SOFI: { company: '소파이 테크놀로지스', country: '' },
  ARE: { company: '알렉산드리아 리얼 에스테이트 에퀴티스', country: '' },
  AZPN: { company: '아스펜 테크놀로지', country: '' },
  MAS: { company: '매스코', country: '' },
  USFD: { company: 'US 푸즈 홀딩', country: '' },
  EQH: { company: '에퀴터블 홀딩스', country: '' },
  CLS: { company: '셀레스티카', country: 'CA' },
  OKTA: { company: '옥타', country: '' },
  OMC: { company: '옴니콤 그룹', country: '' },
  WMG: { company: '워너 뮤직 그룹', country: '' },
  PAGP: { company: '플레인스 GP 홀딩스', country: '' },
  FLEX: { company: '플렉스', country: '' },
  GPC: { company: '제뉴인 파츠', country: '' },
  RBA: { company: 'RB 글로벌', country: '' },
  HOLX: { company: '홀로직', country: '' },
  J: { company: '제이콥스 솔루션스', country: '' },
  BAH: { company: '부즈 알렌 해밀턴 홀딩', country: '' },
  CAVA: { company: '카바 그룹', country: '' },
  PNR: { company: '펜테어', country: 'GB' },
  ICLR: { company: '아이콘', country: 'IE' },
  GFI: { company: '골드 필즈', country: 'ZA' },
  ALGN: { company: '얼라인 테크놀로지', country: '' },
  AU: { company: '앵글로골드 아샨티', country: 'GB' },
  SUI: { company: '선 커뮤니티즈', country: '' },
  HRL: { company: '호멜 푸즈', country: '' },
  BAX: { company: '박스터 인터내셔널', country: '' },
  DG: { company: '달러 제네럴', country: '' },
  FNF: { company: '피델리티 내셔널 파이낸셜', country: '' },
  DLTR: { company: '달러 트리', country: '' },
  CASY: { company: '케이시스 제너럴 스토어스', country: '' },
  XPO: { company: '엑스포', country: '' },
  FIX: { company: '컴포트 시스템즈 USA', country: '' },
  RPM: { company: 'RPM 인터내셔널', country: '' },
  UTHR: { company: '유나이티드 테라퓨틱스', country: '' },
  CHWY: { company: '츄이', country: '' },
  TLK: { company: '텔콤 인도네시아', country: 'ID' },
  DPZ: { company: '도미노 피자', country: '' },
  CNH: { company: 'CNH 인더스트리얼', country: 'GB' },
  WES: { company: '웨스턴 미드스트림 파트너스', country: '' },
  ENTG: { company: '인테그리스', country: '' },
  EXPD: { company: '익스페디터스 인터내셔널 오브 워싱턴', country: '' },
  SN: { company: '샤크닌자', country: '' },
  OC: { company: '오웬스 코닝', country: '' },
  CF: { company: 'CF 인더스트리스 홀딩스', country: '' },
  CSL: { company: '칼라일', country: '' },
  JEF: { company: '제프리스 파이낸셜 그룹', country: '' },
  RS: { company: '릴라이언스', country: '' },
  RL: { company: '랄프 로렌', country: '' },
  LNT: { company: '얼라이언트 에너지', country: '' },
  SMMT: { company: '서밋 테라퓨틱스', country: '' },
  NBIX: { company: '뉴로크린 바이오사이언시스', country: '' },
  BALL: { company: '볼', country: '' },
  RCI: { company: '로저스 커뮤니케이션스', country: 'CA' },
  H: { company: '하얏트 호텔', country: '' },
  UMC: { company: '유나이티드 마이크로일렉트로닉', country: 'TW' },
  YPF: { company: 'YPF', country: 'AR' },
  AKAM: { company: '아카마이 테크놀로지', country: '' },
  RGA: { company: '리인슈어런스 그룹 오브 아메리카', country: '' },
  KIM: { company: '킴코 리얼티', country: '' },
  LOGI: { company: '로지텍 인터내셔널', country: 'CH' },
  AVTR: { company: '어밴터', country: '' },
  IEX: { company: '아이덱스', country: '' },
  EVRG: { company: '에버지', country: '' },
  ARCC: { company: '아레스 캐피탈', country: '' },
  BAP: { company: '크레디코프', country: 'PE' },
  RVTY: { company: '레비티', country: '' },
  AVY: { company: '에이버리 데니슨', country: '' },
  AMCR: { company: '앰코', country: 'GB' },
  'BF-A': { company: '브라운 포먼 A', country: '' },
  'BF-B': { company: '브라운 포먼 B', country: '' },
  EG: { company: '에베레스트 그룹', country: 'BM' },
  EPAM: { company: '이팸 시스템즈', country: '' },
  DVA: { company: '다비타', country: '' },
  INCY: { company: '인사이트', country: '' },
  APTV: { company: '앱티브', country: 'IE' },
  DOC: { company: '헬스피크 프로퍼티스', country: '' },
  SWKS: { company: '스카이웍스 솔루션스', country: '' },
  UDR: { company: 'UDR', country: '' },
  TXT: { company: '텍스트론', country: '' },
  MRNA: { company: '모더나', country: '' },
  REG: { company: '리젠시 센터스', country: '' },
  SWK: { company: '스탠리 블랙 앤 데커', country: '' },
  VTRS: { company: '비아트리스', country: '' },
  SOLV: { company: '솔벤텀', country: '' },
  POOL: { company: '풀', country: '' },
  KMX: { company: '카맥스', country: '' },
  BXP: { company: '보스턴 프로퍼티스', country: '' },
  JKHY: { company: '잭 헨리 앤 어소시에이츠', country: '' },
  CPT: { company: '캠든 프로퍼티', country: '' },
  NCLH: { company: '노르웨이지안 크루즈 라인 홀딩스', country: 'BM' },
  NDSN: { company: '노드슨', country: '' },
  CAG: { company: '콘아그라 브랜즈', country: '' },
  TECH: { company: '바이오-테크네', country: '' },
  JNPR: { company: '주니퍼 네트웍스', country: '' },
  EMN: { company: '이스트만 케미컬', country: '' },
  PAYC: { company: '페이컴 소프트웨어', country: '' },
  CHRW: { company: 'CH 로빈슨 월드와이드', country: '' },
  HST: { company: '호스트 호텔 앤 리조트', country: '' },
  UHS: { company: '유니버셜 헬스 서비스', country: '' },
  ALLE: { company: '얼리젼', country: 'IE' },
  CPB: { company: '캠벨스', country: '' },
  SJM: { company: 'J.M. 스머커', country: '' },
  AIZ: { company: '어슈런트', country: '' },
  TAP: { company: '몰슨 쿠어스 베버리지', country: '' },
  BEN: { company: '프랭클린 리소시스', country: '' },
  IPG: { company: '인터퍼블릭 그룹', country: '' },
  DAY: { company: '데이포스', country: '' },
  GL: { company: '글로브 라이프', country: '' },
  HSIC: { company: '헨리 셰인', country: '' },
  MGM: { company: 'MGM 리조트 인터내셔널', country: '' },
  PNW: { company: '피너클 웨스트 캐피탈', country: '' },
  BG: { company: '번지 글로벌', country: '' },
  LKQ: { company: 'LKQ', country: '' },
  AOS: { company: 'A O 스미스', country: '' },
  FRT: { company: '페더럴 리얼티 인베스트먼트 트러스트', country: '' },
  ALB: { company: '알버말', country: '' },
  WYNN: { company: '윈 리조트', country: '' },
  MOS: { company: '모자이크', country: '' },
  ENPH: { company: '엔페이즈 에너지', country: '' },
  WBA: { company: '월그린스 부츠 얼라이언스', country: '' },
  CRL: { company: '찰스 리버 래보래토리즈 인터내셔널', country: '' },
  GNRC: { company: '제네락 홀딩스', country: '' },
  MTCH: { company: '매치 그룹', country: '' },
  LW: { company: '램 웨스턴 홀딩스', country: '' },
  IVZ: { company: '인베스코', country: '' },
  HAS: { company: '해즈브로', country: '' },
  APA: { company: 'APA', country: '' },
  TFX: { company: '텔레플렉스', country: '' },
  CZR: { company: '시저스 엔터테인먼트', country: '' },
  PARA: { company: '파라마운트 글로벌', country: '' },
  HII: { company: '헌팅턴 잉걸스 인더스트리스', country: '' },
  CE: { company: '셀라니즈', country: '' },
  MHK: { company: '모호크 인더스트리스', country: '' },
  MKTX: { company: '마켓액세스 홀딩스', country: '' },
  AES: { company: 'AES', country: '' },
  BWA: { company: '보그워너', country: '' },
  FMC: { company: 'FMC', country: '' },
  MNDY: { company: '먼데이닷컴', country: 'IL' },
  SMR: { company: '뉴스케일파워', country: '' },
  OKLO: { company: '오클로', country: '' },
  RGTI: { company: '리게티 컴퓨팅', country: '' },
  IONQ: { company: '아이온큐', country: '' },
  LAES: { company: '실SQ', country: 'CH' },
  GME: { company: '게임스탑', country: '' },
  SOUN: { company: '사운드하운드 AI', country: '' },
  RIVN: { company: '리비안 오토모티브', country: '' },
  HIMS: { company: '힘스 앤 허스 헬스', country: '' },
  SPR: { company: '스피릿 에어로시스템즈', country: '' },
  GAP: { company: '갭', country: '' },
  TTAN: { company: '서비스타이탄', country: '' },
  CIEN: { company: '시에나', country: '' },
  CRWV: { company: '코어위브', country: '' },
};
